name: Dynamic Scheduler Tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
        clean: false

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libfl-dev git
        sudo apt-get install gcc-11 g++-11
        sudo apt-get install python3-pip python3-setuptools
        sudo pip3 install robotframework==3.2.2 robotframework-pabot

    - name: Build Verilator
      env:
        CC: gcc-11
        CXX: g++-11
      run: |
        cd verilator
        git show
        autoconf
        ./configure
        make -j$(nproc)
        sudo make install
    - name: Verilator version
      run: |
        verilator --version

    - name: Build vcddiff
      run: |
        git clone https://github.com/veripool/vcddiff
        make -C vcddiff
        sudo cp -p vcddiff/vcddiff /usr/local/bin

    - name: Generate Robot Tests
      env:
        CC: gcc-11
        CXX: g++-11
      run: ./gen_robot.py
    - name: Run Robot Tests
      env:
        CC: gcc-11
        CXX: g++-11
      run: pabot --processes $(($(nproc) + 1)) --verbose --testlevelsplit --noncritical should_fail --noncritical dist --noncritical opt --noncritical perf --noncritical file_grep --noncritical debug_out --noncritical code_gen  robot_tests || true

    - name: Show Diff In Results
      run: |
        git fetch origin gh-pages
        ./compare_robot_logs.py <(git show origin/gh-pages:output.xml) output.xml | tee diff.log

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: robot_logs
        path: |
          report.html
          output.xml
          log.html
          diff.log

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        mkdir deploy
        mv report.html output.xml log.html diff.log deploy
        touch deploy/.nojekyll
        echo '<head> <meta http-equiv="refresh" content="0; url=report.html" /> </head>' > deploy/index.html
        cd deploy
        git init
        cp ../.git/config ./.git/config
        git add .
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git commit -am "update ${{ github.sha }}"
        git push -u origin +HEAD:gh-pages
        rm -rf .git

  swerv:
    runs-on: ubuntu-latest
    needs: build
    env:
      CC: gcc-11
      CXX: g++-11

    steps:
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt install -y g++-11 build-essential python3 python3-pip google-perftools libelf-dev ninja-build git
          update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries

      # See https://github.com/actions/upload-artifact/issues/38
      - name: Extract
        run: tar -xf binaries.tar

      - name: Build & Test
        run: |
          export RV_ROOT=${PWD}/design_tests/swerv/Cores-SweRV
          make -f ${RV_ROOT}/tools/Makefile VERILATOR=${PWD}/verilator/bin/verilator
