name: Dynamic Scheduler Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libfl-dev git
    - name: Build Verilator
      run: |
        cd verilator
        git show
        autoconf
        ./configure
        make -j$(nproc)
        sudo make install
    - name: Verilator version
      run: |
        verilator --version
    - name: Dedicated tests
      run: ./test_all.sh
    - name: Built-in regression tests
      run: |
        cd verilator/test_regress
        make test -j$(nproc)
