name: Dynamic Scheduler Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
        clean: false
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libfl-dev git
        sudo apt-get install gcc-10 g++-10
        sudo apt install python3-pip
        sudo pip3 install robotframework

    - name: Build Verilator
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        cd verilator
        git show
        autoconf
        ./configure
        make -j$(nproc)
        sudo make install
    - name: Verilator version
      run: |
        verilator --version

    - name: Generate Robot tests
      env:
        CC: gcc-10
        CXX: g++-10
      run: ./gen_robot.py
    - name: Run Robot tests
      env:
        CC: gcc-10
        CXX: g++-10
      run: robot all_tests.robot || true

    - uses: actions/upload-artifact@v2
      with:
        name: robot_logs
        path: |
          report.html
          output.xml
          log.html
