name: Dynamic Scheduler Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
        clean: false
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libfl-dev git
        sudo apt-get install gcc-10 g++-10
    - name: Build Verilator
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        cd verilator
        git show
        autoconf
        ./configure
        make -j$(nproc)
        sudo make install
    - name: Verilator version
      run: |
        verilator --version
    - name: Dedicated tests
      env:
        CC: gcc-10
        CXX: g++-10
      run: ./test_all.sh
    - name: Built-in regression tests
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        cd verilator/test_regress
        make test -j$(nproc)
