name: Dynamic Scheduler Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libfl-dev
    - name: Build Verilator
      run: |
        cd verilator
        autoconf
        ./configure
        make -j$(nproc)
        sudo make install
    - name: Run tests
      run: ./test_all.sh
